config/routes.rb
Rails.application.routes.draw do

  root 'blogs#index'

  resources :blogs, shallow: true do
    resources :articles
  end

  resources :articles, only: [:index, :edit, :update], shallow: true do
    resources :comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :blog
  has_many :comments, dependent: :destroy

  validates :title, presence: true,
            length: { minimum: 5 }
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :articles, dependent: :destroy

  validates :name, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  #http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]

  def index
    @articles = Article.all.select { |article| article.blog_id.present? }
    @unassigned_articles = Article.all.where(blog_id: nil)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @blog = Blog.find(params[:blog_id])
    @article = @blog.articles.new
  end

  def edit
    #@blog = Blog.find(params[:blog_id])
    @article = Article.find(params[:id])
  end

  def create
    @blog = Blog.find(params[:blog_id])
    @article = @blog.articles.new(article_params)

    if @article.save
      redirect_to @blog
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article.blog
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    @article.blog ? redirect_to(blog_path(@article.blog)) : redirect_to(articles_path)
  end

  private
  def article_params
    params.require(:article).permit(:title, :text, :blog_id)
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blogs = Blog.all
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def new
    @blog = Blog.new
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def create
    @blog = Blog.new(blog_params)

    if @blog.save
      redirect_to @blog
    else
      render 'new'
    end
  end

  def update
    @blog = Blog.find(params[:id])

    if @blog.update(blog_params)
      redirect_to blogs_path
    else
      render 'edit'
    end
  end

  def destroy
    @blog = Blog.find(params[:id])

    @blog.destroy
    redirect_to blogs_path
  end

  private
  def blog_params
    params.require(:blog).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  #http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to article_path(@comment.article)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.erb
<%= form_for [@blog, @article] do |f| %>

    <div class="form-group has-error">
      <% if @article.errors.any? %>
          <div id="error_explanation">
            <h3 class="control-label">
              <%= pluralize(@article.errors.count, "error") %> prohibited
              this article from being saved:
            </h3>
            <ul>
              <% @article.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
    </div>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :text %><br>
      <%= f.text_area :text, class: "form-control", rows: "3" %>
    </p>

    <%= f.select(:blog_id, Blog.all.collect { |p| [p.name, p.id] }, @article.blog_id ? {} : {selected: @article.blog_id}) %>

    <p>
      <%= f.submit class: "btn-primary" %>
    </p>

<% end %>

app/views/articles/_table.erb
<% if items.empty? %>
    <h1>Table is empty</h1>

<% else %>
    <div class="container">
      <table class="table table-hover">
        <tr>
          <th class="col-md-2">#</th>
          <th class="col-md-3">Title</th>
          <th class="col-md-5">Text</th>
          <th class="col-md-2">Blog</th>
        </tr>

        <% items.each do |item| %>
            <tr>
              <td> <%= item.id %> </td>
              <td> <%= item.title %> </td>
              <td> <%= item.text %> </td>
              <td>
                <%= item.blog.name if item.blog.present? %>
                <%= link_to('Assign', edit_article_path(item))  if !item.blog.present?%>
                <%= link_to('Remove', article_path(item), method: :delete, data: {confirm: 'Are you sure?'})  if !item.blog.present?%>
              </td>
            </tr>
        <% end %>

      </table>
    </div>
<% end %>

app/views/articles/edit.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/articles/index.erb
<h1>List of Articles</h1>

<%= render partial: "table", object: @articles, as: "items" %>

<h1>List of unassigned Articles</h1>
<p class="text-muted">(Assign blog to article or delete)</p>

<%= render partial: "table", object: @unassigned_articles, as: "items" %>

app/views/articles/new.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_path(@blog) %>

app/views/articles/show.erb
<p class="bg-primary" text-align="center">
  <%= @article.title %>
</p>

<p>
  <%= @article.text %>
</p>

<h3>Comments</h3>
<%= render @article.comments %>

<h4>Add a comment:</h4>
<%= render 'comments/form' %>

<%= link_to 'Back to Blog', blog_path(@article.blog) %>

app/views/blogs/_form.erb
<% if @blog.errors.any? %>
    <ul>
      <% @blog.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
      <% end %>
    </ul>

<% end %>

<%= form_for @blog do |f| %>
    <p>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </p>
    <%= f.submit class: "btn-primary"%>
<% end %>

app/views/blogs/edit.erb
<h1>Edit Blog#<%= @blog.id %></h1>

<%= render 'form' %>

<%= link_to 'Back to the list of blogs', blogs_path%>

app/views/blogs/index.erb
<div>
  <div class="col-md-8"><h1>List of Blogs</h1></div>
  <div class="col-md-4" align="right"><%= link_to 'Create new blog', new_blog_path%></div>
</div>

<% if @blogs.empty? %>
    <h3>No Blogs in app</h3>

<% else %>
    <div>
      <table class="table table-hover">
        <tr>
          <th class="col-md-2">#</th>
          <th class="col-md-5">Blog name</th>
          <th class="col-md-5">Actions</th>
        </tr>

        <% @blogs.each do |blog| %>
            <tr>
              <td> <%= @blogs.index(blog) + 1 %> </td>
              <td> <%= link_to blog.name, blog_path(blog) %> </td>
              <td> <%= link_to 'Edit', edit_blog_path(blog) %> <%= link_to 'Remove', blog_path(blog),
                                                                           method: :delete,
                                                                           data: {confirm: 'Are you sure?'} %> </td>
            </tr>
        <% end %>

      </table>
    </div>
<% end %>

app/views/blogs/new.erb
<h1>Creating new Blog</h1>

<%= render 'form' %>

<%= link_to 'Back to the list of blogs', blogs_path%>

app/views/blogs/show.erb
<div>
  <div class="col-md-8"><h1>Blog #<%= @blog.id %> - <%= @blog.name %></h1></div>
  <div class="col-md-4" align="right"><%= link_to 'Create new article', new_blog_article_path(@blog) %></div>
</div>


<% if @blog.articles.empty? %>
    <h3>No articles for this blog</h3>

<% else %>
    <div>
      <table class="table table-hover">
        <tr>
          <th class="col-md-2">#</th>
          <th class="col-md-3">Title</th>
          <th class="col-md-4">Text</th>
          <th class="col-md-3">Actions</th>
        </tr>
        <% @blog.articles.each do |article| %>
            <tr>
              <td> <%= @blog.articles.index(article) + 1 %> </td>
              <td> <%= link_to article.title, article_path(article) %> </td>
              <td> <%= article.text %> </td>
              <td> <%= link_to 'Edit', edit_article_path(article) %> <%= link_to 'Remove', article_path(article),
                                                                                             method: :delete,
                                                                                             data: {confirm: 'Are you sure?'} %> </td>
            </tr>
        <% end %>
      </table>
    </div>

<% end %>

<%= link_to 'Back to the list of blogs', blogs_path %>

app/views/comments/_comment.erb
<div class="container">
  <div class="col-md-4">

    <p>
    <h4><%= comment.commenter %>
      <small>(<%= comment.created_at.strftime("%B %d, %Y") %>)</small>
    </h4>
    </p>

    <p>
      <%= comment.body %>
    </p>

    <p>
      <%= link_to 'Remove Comment', [comment],
                  method: :delete,
                  data: {confirm: 'Are you sure?'} %>
    </p>

  </div>

  <div class="col-md-4"></div>

</div>

<hr>

app/views/comments/_form.erb
<%= form_for([@blog, @article, @article.comments.build]) do |f| %>
    <p>
      <%= f.label :commenter %><br>
      <%= f.text_field :commenter %>
    </p>
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="container">

<div class="container">
  <nav class="navbar navbar-default">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li> <%= link_to "Blogs", blogs_path %> </li>
        <li> <%= link_to "Articles", articles_path %> </li>
      </ul>
    </div>
  </nav>
</div>

<div class="container">
  <%= yield %>
</div>

<div class="container">
  <%= params.inspect %>
</div>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', blogs_path %>